Creates new directory focus with 3 blank files and new folder
jmuratov98/OS-Final-Project pull request #3
Opened 2020-04-15 18:17 UTC by GHJon

2020-04-15 18:51 UTC, jmuratov98 approved these changes

2020-04-19 02:15 UTC, JiejayLan commented on tree*.c
> +}
need a new line at the end

2020-04-19 02:17 UTC, JiejayLan requested changes
Check my comments, the logic should not have big issues

2020-04-19 02:17 UTC, JiejayLan commented on tree*.c
> +    else printf("Failed Opening %s", dirname[0]);
The code for create 3 files are duplicate,  can use a for loop to refactor the logic

2020-05-04 01:46 UTC, JiejayLan approved these changes
Nothing I can say

2020-05-04 01:46 UTC, merged